CREATE DATABASE ptsi_mikhaelbitelo;
USE ptsi_mikhaelbitelo;
CREATE TABLE situacao(
    idSituacao INT NOT NULL AUTO_INCREMENT,
    nomeSituacao VARCHAR(15) NOT NULL,
    constraint pk_situacao PRIMARY KEY (idSituacao)
);

CREATE TABLE animal(
    idAnimal INT NOT NULL AUTO_INCREMENT,
    nomeAnimal VARCHAR(20) NOT NULL,
    constraint pk_animal PRIMARY KEY (idAnimal)
);

CREATE TABLE raca(
    idRaca INT NOT NULL AUTO_INCREMENT,
    nomeRaca VARCHAR(40) NOT NULL,
    idAnimal INT NOT NULL,
    constraint pk_raca PRIMARY KEY (idRaca),
    constraint fk_racani FOREIGN KEY (idAnimal) references animal(idAnimal)
);

CREATE TABLE evento(
    idEvento INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(20),
    idade VARCHAR(20),
    caracteristicas VARCHAR(150) NOT NULL,
    local VARCHAR(50) NOT NULL,
    dataEvento DATE NOT NULL,
    pessoa VARCHAR(50) NOT NULL,
    contato VARCHAR(100) NOT NULL,
    idRaca INT NOT NULL,
    imagem VARCHAR(30) NOT NULL,
    dataPost DATETIME NOT NULL,
    publicado BOOLEAN NOT NULL,
    idSituacao INT NOT NULL,
    CONSTRAINT pk_evento PRIMARY KEY (idEvento),
    CONSTRAINT fk_everac FOREIGN KEY (idRaca) REFERENCES raca(idRaca),
    CONSTRAINT fk_evesit FOREIGN KEY (idSituacao) REFERENCES situacao(idSituacao)
);

CREATE TABLE registro_reset(
    idRegistro INT NOT NULL AUTO_INCREMENT,
    datahora DATETIME NOT NULL,
    CONSTRAINT pk_registro_reset PRIMARY KEY (idRegistro)
);

INSERT INTO situacao (nomeSituacao) VALUES
    ('Perdido'),
    ('Encontrado');


INSERT INTO animal (nomeAnimal) VALUES
('Cachorro'),
('Gato'),
('Ave'),
('Outros');

INSERT INTO raca(idAnimal, nomeRaca) VALUES
(1,'SRD - Sem Raça Definida'),
(1,'Alano Espanhol'),
(1,'Airedale Terrier'),
(1,'American Staffordshire Terrier'),
(1,'American Water Spaniel'),
(1,'Antigo Cão de Pastor Inglês'),
(1,'Basset Azul da Gasconha'),
(1,'Basset Fulvo da Bretanha'),
(1,'Basset Hound'),
(1,'Beagle'),
(1,'Bearded Collie'),
(1,'Bichon Maltês'),
(1,'Bobtail'),
(1,'Border Collie'),
(1,'Boston Terrier'),
(1,'Boxer'),
(1,'Bull Terrier'),
(1,'Bullmastiff'),
(1,'Bulldog'),
(1,'Cão de Montanha dos Pirinéus'),
(1,'Caniche'),
(1,'Chihuahua'),
(1,'Cirneco do Etna'),
(1,'Chow Chow'),
(1,'Cocker Spaniel (Americano ou Inglês)'),
(1,'Dálmata'),
(1,'Dobermann'),
(1,'Dogue Alemão'),
(1,'Dogue Argentino'),
(1,'Dogue Canário'),
(1,'Fox Terrier'),
(1,'Foxhound'),
(1,'Galgo'),
(1,'Golden Retriever'),
(1,'Gos d\'Atura'),
(1,'Husky Siberiano'),
(1,'Laika'),
(1,'Labrador Retriever'),
(1,'Malamute-do-Alasca'),
(1,'Mastin dos Pirenéus'),
(1,'Mastin do Tibete'),
(1,'Mastin Espanhol'),
(1,'Mastín Napolitano'),
(1,'Pastor Alemão'),
(1,'Pastor Belga'),
(1,'Pastor de Brie'),
(1,'Pastor dos Pirenéus de Cara Rosa'),
(1,'Pequinês'),
(1,'Perdigueiro'),
(1,'Pitbull'),
(1,'Podengo'),
(1,'Pointer'),
(1,'Pug'),
(1,'Rhodesian Ridgeback'),
(1,'Rottweiler'),
(1,'Rough Collie'),
(1,'Sabueso (Espanhol ou Italiano)'),
(1,'Saluki'),
(1,'Samoiedo'),
(1,'São Bernardo'),
(1,'Scottish Terrier'),
(1,'Setter Irlandés'),
(1,'Shar-Pei'),
(1,'Shiba Inu'),
(1,'Smooth Collie'),
(1,'Staffordshire Bull Terrier'),
(1,'Teckel'),
(1,'Terra-nova'),
(1,'Terrier Australiano'),
(1,'Terrier Escocês'),
(1,'Terrier Irlandês'),
(1,'Terrier Japonês'),
(1,'Terrier Negro Russo'),
(1,'Terrier Norfolk'),
(1,'Terrier Norwich'),
(1,'Terrier Tibetano'),
(1,'Welhs Terrier'),
(1,'West Highland T.'),
(1,'Wolfspitz'),
(1,'Yorkshire Terrier'),
(1,'Outro'),
(2,'SRD - Sem Raça Definida'),
(2,'Abissínio'),
(2,'Angorá turco'),
(2,'American curl.'),
(2,'American Shorthair.'),
(2,'American wirehair'),
(2,'Azul russo'),
(2,'Balinês'),
(2,'Bengal'),
(2,'Bobtail Japonês'),
(2,'Bombay'),
(2,'British Shorthair'),
(2,'Burmês'),
(2,'Burmês Europeu'),
(2,'California spangled'),
(2,'Chartreux'),
(2,'Cornish rex'),
(2,'Devon Rex'),
(2,'Exótico'),
(2,'Habana'),
(2,'Himalayan'),
(2,'Javanês'),
(2,'Korat'),
(2,'Maine coon'),
(2,'Manx'),
(2,'Mau Egípcio N'),
(2,'Nibelungo'),
(2,'Noruega da floresta'),
(2,'Ocicat'),
(2,'Oriental de pêlo curto'),
(2,'Persa'),
(2,'Ragamuffin'),
(2,'Ragdoll'),
(2,'Sagrado da Birmânia'),
(2,'Scottish fold'),
(2,'Selkirk rex'),
(2,'Siamês'),
(2,'Singapur'),
(2,'Shorthair Americano'),
(2,'Shorthair Britânico'),
(2,'Shorthair Exótico'),
(2,'Snowshoe'),
(2,'Somali'),
(2,'Sphynx'),
(2,'Tiffanie'),
(2,'Tonquinês'),
(2,'Van turco'),
(2,'Outro'),
(3,'Periquito'),
(3,'Canário'),
(3,'Calopsita'),
(3,'Manon'),
(3,'Diamente Gold'),
(3,'Mandarin'),
(4,'Cavalo'),
(4,'Tartaruga'),
(4,'Hamster'),
(4,'Aranha'),
(4,'Coelho'),
(4,'Porquinho-da-índia'),
(4,'Outro');

INSERT INTO `evento` (`idEvento`, `nome`, `idade`, `caracteristicas`, `local`, `dataEvento`, `pessoa`, `contato`, `idRaca`, `imagem`, `dataPost`, `publicado`, `idSituacao`) VALUES
(01, 'Bob', '1 Ano', 'Pêlos acinzentados e longos', 'Centro Gravataí', '2019-05-18', 'Maria Joaquina', '51 2222-2222', 112, '15572671765cd202e8453ec.jpg', '2019-05-19', 0, 1),
(02, 'Scooby', '3 anos e meio', 'Tem uma mancha na barriga', 'Parcão de Cachoeirinha', '2019-05-20', 'Dafine', '51 4444-4444 ou procuroscooby@melhoremail.com', 28, '15572671955cd202fb09624.jpg', '2019-05-27', 0, 1),
(03, 'Ligeiro', '5 meses', 'pequeno porte', 'Bairro Santa Cruz, próximo ao Supermercado', '2019-05-26', 'Carlos Eduardo', 'cadu@email.com.br', 140, '15572672695cd20345a4b27.jpg', '2019-05-28', 1, 1),
(04, 'Esmeralda', '10 anos', 'Tem uma cicatriz grande na cabeça, olhos bem verdes', 'Em frente a Universidade', '2019-05-16', 'Alvarez Cabral', 'descobrimento@brasil.com', 118, '15572672835cd20353e8cc3.jpg', '2019-05-18', 0, 1),
(05, 'Rex', '2 anos e 3 meses', 'Docil, estava com um lenço de patas no pescoço', 'Rua dos Bobos, numero 0', '2019-05-23', 'Joaquim', '51 888.888.888', 50, '15572673255cd2037d331a6.jpg', '2019-05-24', 1, 1),
(06, '', '', 'Plumagem clara', 'Shopping de Gravataí', '2019-05-29', 'Luiz Mário', '51 3333-3333', 132, '15572673405cd2038c9604f.jpg', '2019-06-03', 1, 2),
(07, 'Teco', 'de 5 a 7 anos', 'Está com uma coleira preta com o nomenuma DogTag', 'Alphaville', '2019-05-24', 'João Paulo', 'joaopaulo@melhoremail.com', 1, '15572673685cd203a863fe2.jpg', '2019-05-24', 0, 2),
(08, '', '', 'pequenino e peludinho', 'Bairro Dom Feliciano, próximo à escola', '2019-05-30', 'Bento', '51 999.999.999', 138, '15572673855cd203b985fbd.jpg', '2019-06-01', 0, 2);